{
  "hash": "8868399f27d95bbcdac0bb94623f8320",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 5:  Kaplan–Meier estimate of the survival functions and Cox regression model\"\nformat: \n    html:\n        echo: false\n---\n\n\n::: hidden\n$$\n  \\renewcommand{\\P}{\\mathbb{P}}\n  \\newcommand{\\E}{\\mathbb{E}}\n$$\n:::\n\n\n# Reminder about data frames\n\n##\n:::{.task}\nDownload [hm.csv](hm.csv) file, store it at the variable `df`, and show first rows of the data set. Check the output.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID time age drug status    entdate    enddate\n1  1    5  46    0      1 15/05/2015 14/10/2015\n2  2    6  35    1      0 19/09/2014 20/03/2015\n3  3    8  30    1      1 21/04/2016 20/12/2016\n4  4    3  30    1      1 03/01/2016 04/04/2016\n5  5   22  36    0      1 18/09/2014 19/07/2016\n6  6    1  32    1      0 18/03/2016 17/04/2016\n```\n\n\n:::\n:::\n\n\nAs you can see, this data frame contains some data about patients, who were in a trial. Column \"time\" tells us how many full months the trial took place place for each patient (we know that it's \"months\" time units looking at the last two columns: \"entdate\" is the dat of the start of the trial for a patient, and the \"enddate\" is the date of the end of the trial). Column \"age\"  contains obviously their ages. Column \"drug\" tells us whether they got some medicine effect of which we investigate ($0$ means no, $1$ means yes). Column \"status\" tells us their status at the end of the trial: $1$ stands for \"dead\" (because of the drug received), $0$ means \"not dead because of the drug\", i.e. censored (excluded from the trial, e.g. recovered and dismissed, or dead by another reason non related to the drug, or something else).\n\n##\n:::{.task}\nFind the mean age of the participants of the trial. Check the answer\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.07\n```\n\n\n:::\n:::\n\n\n##\n:::{.task}\nFind the number of entries (rows) in the data frame. Check the answer:\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\n# Kaplan–Meier estimate \n\nTo build the Kaplan-Meier estimate of the survival function based on the data, we will use package `survival`. Install it, using menu `Tools` in R Studio and then choosing `Install Packages` item. Load the installed package in your code:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(survival)\n```\n:::\n\n\nFirst, we need to \"label\" the data, explaining which entries are censored. For this we use the function `Surv` (notice the first capital letter!) which has (at least) two arguments, e.g. `Surv(time, status)`. Here `time` is a vector containing the data (normally, moments of time), in the example above this data is in the column `df$time`. Next, `status` in the `Surv` function is e.g. a vector of 0/1 or 1/2 where the larger number (1 for 0/1 or 2 for 1/2) means the death because of the considered reason (drug in this example). In our example, we have for this the column `df$status`. The output is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nSurv(df$time, df$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1]  5   6+  8   3  22   1+  7   9   3  12   2+ 12   1  15  34   1   4  19+\n [19]  3+  2   2+  6  60+ 11   2+  5   4+  1  13   3   2   1  30   7   4   8 \n [37]  5  10   2   9  36   3   9   3  35   8  11  56+  2+  3  15   1  10   1 \n [55]  7   3   3   2  32   3  10+ 11   3   7   5  31   5  58   1   3+ 43   1 \n [73]  6  53  14   4  54   1   1   8   5   1   1   2   7+  1+ 10  24+  7  12+\n [91]  4  57   1  12+  7   1   5  60+  2+  1 \n```\n\n\n:::\n:::\n\n\nAs you can see all censored moments of time got \"+\" label. Note that the output of `Surv` function is the so-called \"survival object\" which has some special internal structure used by R, what we see above is just a visual representation.\n\nNext, to build the Kaplan-Meier estimate of the survival function based on the given data, we use function `survfit`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsf <- Surv(df$time, df$status)\nkm <- survfit(sf ~ 1)\nkm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = sf ~ 1)\n\n       n events median 0.95LCL 0.95UCL\n[1,] 100     80      7       5      10\n```\n\n\n:::\n:::\n\n\nThe symbols `~ 1` means that we want to build the Kaplan-Meier estimate for the whole (non-censored) data from the data frame regardless of other covariates (characteristics) like age or whether the patient got the drug. The output of `survfit` (which we stored in `km` variable) tells us that for $n=100$ patients only $80$ events happened (meaning, in this example, non-censored deaths, i.e. deaths because fo the drug). Again, the output of `survfit` (stored in `km`) contains more information, we se only part of it. The usage of this outpus is as follows:\n\nFirst, we can plot the Kaplan-Meier estimate:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(km)\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe solid (middle) line here is actually the graph of the the Kaplan-Meier estimate for the survival function for the given data. The dashed lines show the boundaries of the $0.95$-confidence interval for such survival functions. It means that the given data is, obviously, just a sample from some large population of patients which got this drug in similar circumnstances (e.g. after the same decease or the same surtgery etc.). If we (hypothetically) would take a large number of samples from this populations (all samples should be of the same length $100$ like in the our example), and if we would plot the Kaplan-Meier estimates for the survival functions in each such sample, then $95$% of these curves would be in the area bounded by the dashed curves on the plot above. \n\nNote that the value $0.95$ for the confidence interval is the default value, and it can be changed, e.g.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(survfit(sf ~ 1), conf.int = 0.99)\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nAs you can see, the area is now \"wider\" as it should cover a larger number of samples ($99$%).\n\n\nNext, we can use the output of `survfit` to investigate numerical values of the Kaplan-Meier estimate:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsummary(km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = sf ~ 1)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1    100      15   0.8500  0.0357       0.7828        0.923\n    2     83       5   0.7988  0.0402       0.7237        0.882\n    3     73      10   0.6894  0.0473       0.6026        0.789\n    4     61       4   0.6442  0.0493       0.5544        0.748\n    5     56       7   0.5636  0.0517       0.4709        0.675\n    6     49       2   0.5406  0.0521       0.4476        0.653\n    7     46       6   0.4701  0.0526       0.3775        0.586\n    8     39       4   0.4219  0.0525       0.3306        0.538\n    9     35       3   0.3857  0.0520       0.2962        0.502\n   10     32       3   0.3496  0.0511       0.2625        0.466\n   11     28       3   0.3121  0.0500       0.2280        0.427\n   12     25       2   0.2872  0.0490       0.2055        0.401\n   13     21       1   0.2735  0.0486       0.1931        0.387\n   14     20       1   0.2598  0.0480       0.1809        0.373\n   15     19       2   0.2325  0.0467       0.1568        0.345\n   22     16       1   0.2179  0.0460       0.1441        0.330\n   30     14       1   0.2024  0.0453       0.1305        0.314\n   31     13       1   0.1868  0.0444       0.1173        0.298\n   32     12       1   0.1712  0.0433       0.1043        0.281\n   34     11       1   0.1557  0.0421       0.0916        0.264\n   35     10       1   0.1401  0.0407       0.0793        0.247\n   36      9       1   0.1245  0.0390       0.0674        0.230\n   43      8       1   0.1090  0.0371       0.0559        0.212\n   53      7       1   0.0934  0.0349       0.0449        0.194\n   54      6       1   0.0778  0.0324       0.0344        0.176\n   57      4       1   0.0584  0.0296       0.0216        0.157\n   58      3       1   0.0389  0.0253       0.0109        0.139\n```\n\n\n:::\n:::\n\n\nIn the output of `summary`, column `time` contains the times (the lengths of trials) when non-cesored deaths happened. Column `n.risk` contains numer of patients who were still under investigation at those times (more precisely, right before those times), and `n.event` is the number of non-censored deaths which happened at those times. The column `survival` contains the desired values of the Kaplan-Meier estimate, i.e.\n\n$$\n\\hat{S}(k)=\\mathtt{survival}(\\mathtt{time} = k) = \\prod_{j\\leq k}\\biggl( 1-\\frac{\\mathtt{n.event}(\\mathtt{time}=j)}{\\mathtt{n.risk}(\\mathtt{time}=j)} \\biggr).\n$$\n\nFor example, the estimate for the probability that a patient would survive at least $38$ months (after the considered event, say, surgery or desease) is $0.1245$. Indeed, since $38$ is between $36$ abd $43$ which are present in the `time` column and the estiamte for the survival function is constant between the given moments of time, then\n\n$$\n\\hat{S}(38)=\\hat{S}(36)= 0.1245.\n$$\n\n##\n:::{.task}\nFind out how likely, for the given data, is to survive at least $17$ months than at least $51$ months. Check your answer.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.133028\n```\n\n\n:::\n:::\n\n\n# Kaplan–Meier estimate for covariates\n\nSuppose now we want to get Kaplan–Meier estimates for survival functions separately for those who got drugs and those who didn't. Instead of writing `~ 1` in `survfit` function discussed above, we will write `~ df$drug`:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsf <- Surv(df$time, df$status)\nkmdrug <- survfit(sf ~ df$drug)\nkmdrug\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = sf ~ df$drug)\n\n           n events median 0.95LCL 0.95UCL\ndf$drug=0 51     42     11       8      30\ndf$drug=1 49     38      5       3       7\n```\n\n\n:::\n:::\n\n\nHence, there are $51$ patients who didn't get drug and $42$ of them aparently died being non-sensored; whereas, there are $49$ patients who got drug and $38$ of them aparently died being non-sensored.\n\nWe can plot both survival functions at once:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(kmdrug)\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nThe problem is only that we do not see which curves is for whom. We can use e.g. different colours and, most importantly, a legend for the plot:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(kmdrug, col=c(\"blue\", \"red\"))\nlegend(\"topright\", legend=c(\"drug=0\",\"drug=1\"), col=c(\"blue\", \"red\"), lty=c(1,1))\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nNote that `lty` inside legend tells to draw lines in the legend, where `1` stands for a solid line (it's a common agreement in R). For e.g. a dashed line, it would be $2$.\n\n##\n:::{.task}\nPlot the previous plot with legend so that `drug=0` whould be in dashed `seagreen` colour (both on plot and in legend) and denoted by \"No drug\", and `drug=1` would be in solid orange and denoted \"drug\".\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n# Embedded data frames\n\nThe data frame `lung` is embedded into `survival` package. You can get information about this data frame by typing in the console `?lung`. \n\nNote that instead of writing e.g.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nkmlung <- survfit(Surv(lung$time, lung$status) ~ lung$sex)\nkmlung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(lung$time, lung$status) ~ lung$sex)\n\n             n events median 0.95LCL 0.95UCL\nlung$sex=1 138    112    270     212     310\nlung$sex=2  90     53    426     348     550\n```\n\n\n:::\n:::\n\none can write\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nkmlung <- survfit(Surv(time, status) ~ sex, data = lung)\nkmlung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time, status) ~ sex, data = lung)\n\n        n events median 0.95LCL 0.95UCL\nsex=1 138    112    270     212     310\nsex=2  90     53    426     348     550\n```\n\n\n:::\n:::\n\nthat is more compact. \n\n##\n:::{.task}\nWrite the code for the following plot:\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nSurely, there numerous R packages which can make plots more nice. For example, may install and load `survminer` package:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(survminer)\nggsurvplot(kmlung)\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\nHere \"strata\" is a synonym for \"covariate\". Moreover, by specifying `conf.int` one can also include the confidence intervals **for both** values of the covariate:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nggsurvplot(kmlung, conf.int = 0.95)\n```\n\n::: {.cell-output-display}\n![](Lab5_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nNote also that if we define `kmlung` **without** `data = lung` then `ggsurvplot` **must include** `data = lung`:\ni.e. the full command would be `ggsurvplot(survfit(Surv(lung$time, lung$status) ~ lung$sex), conf.int = 0.95)`.\n\n \n\n# Cox regression model\n\nIn the above, one had two different estimators for survival functions corresponding to different categories (different values of the covariate `sex`). The Cox regression model is effective to see a unified estimator for the survival function for both categories.\n\nRecall that the Cox model for one covariate takes the form $$ \\lambda(t,z)=\\lambda_0(t)e^{\\beta z}, $$ where $\\beta\\in\\mathbb{R}$. In our case, looking at `?lung`, $z\\in\\{1,2\\}$, where $z=1$ stands for male and $z=2$ stands for female.\n\nFunction `coxph` calculates the estimate for the parameters $\\beta$ and has the same arguments as `survfit` considered above:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfit <- coxph(Surv(time, status)~sex, data=lung)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ sex, data = lung)\n\n       coef exp(coef) se(coef)      z       p\nsex -0.5310    0.5880   0.1672 -3.176 0.00149\n\nLikelihood ratio test=10.63  on 1 df, p=0.001111\nn= 228, number of events= 165 \n```\n\n\n:::\n:::\n\n\nThen, the ratio of hazard rates \n$$ \\frac{\\lambda(t,\\mathrm{female})}{\\lambda(t,\\mathrm{male})}=\\frac{\\lambda_0(t)e^{2\\beta}}{\\lambda_0(t)e^{\\beta}}=e^{\\beta}. $$\n\nIn the output of `fit`, the value of `coef` stands for the maximal likelihood estimator (which we denoted as $\\beta^*$ on lectures), thus, for the maximal likelihood, looking at the value of `exp(coef)`  \n$$  \n\\frac{\\lambda(t,\\mathrm{female})}{\\lambda(t,\\mathrm{male})} = 0.5880,  \n$$  \nIn other words, based on the data set `lung` females with advanced lung cancer has approximately $0.59$ times less hazard rates (a.k.a. the force of mortality) than males (calculated at the same moments of time under the treatment).\n\nNote that the command `summary(fit)` provides more detailed information. In particular, it includes also `exp(-coef)` that is the inverse ratio:\n$$ \n\\frac{\\lambda(t,\\mathrm{male})}{\\lambda(t,\\mathrm{female})}=e^{-\\beta}. \n$$ \n(Surely, it can be obtained manually as the reciprocal: `1/0.5880=1.70068`).\n\nIn the above, we dealt with one covariate, `sex`. To deal with several, the corresponding names should be added, e.g. `~sex+age`: \n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfit2 <- coxph(Surv(time, status)~sex+age, data=lung)\nfit2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ sex + age, data = lung)\n\n         coef exp(coef)  se(coef)      z       p\nsex -0.513219  0.598566  0.167458 -3.065 0.00218\nage  0.017045  1.017191  0.009223  1.848 0.06459\n\nLikelihood ratio test=14.12  on 2 df, p=0.0008574\nn= 228, number of events= 165 \n```\n\n\n:::\n:::\n\n\nHere, if $z_1\\in\\{1,2\\}$ represents sex and $z_2\\in\\mathbb{N}$ represents the age,\n$$ \n\\dfrac{\\lambda(t,z_1,z_2)}{\\lambda(t,\\tilde{z}_1,\\tilde{z}_2)} =\\exp\\bigl(\\beta_1(z_1-\\tilde{z}_1)\\bigr)\\exp\\bigl(\\beta_2(z_2-\\tilde{z}_2)\\bigr). \n$$ \nAs a result, the ratio of hazard rates for the same sex and for two subsequent years is \n$$ \n\\dfrac{\\lambda(t,z_1,z_2+1)}{\\lambda(t,z_1,z_2)} = e^{\\beta_2} = 1.017191, \n$$ \ni.e. each year increases the hazard rate (again, for the people as in the data set) by approximately $1.7$%.\n\n##\n:::{.task}\nFind the ratio of the hazard rate for a male aged 70 to a female aged 80 (for the given data set). Check the asnwer:\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.408844\n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}