project:
  type: website
  output-dir: docs
  render:
    - Lab*.qmd
    - index.qmd

website:
  title: "MA-365/M65 Lab Assignments"
  page-navigation: true
  back-to-top-navigation: true
  description: "Lab Assignments for module MA-365/M65: Risk and Survival Models"
  site-url: "https://finkelshtein.github.io/MA-x65/website/"
  open-graph: true
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Dmitri Finkelshtein"
    center: "MA-365/M65: Lab Assignments"
    background: "#D9E3E4"
  sidebar:
    background: "#D9E3E4"
    logo: "images/graph.jpg"
    pinned: true
    align: center
    
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - href: index.qmd
        text: Site overview
      - text: "---"
      - section: "Labs - Problems"
        contents:
          - href: Lab1.qmd
            text: Lab 1 - Problems
          - href: Lab2.qmd
            text: Lab 2 - Problems
          - href: Lab3.qmd
            text: Lab 3 - Problems
          - href: Lab4.qmd
            text: Lab 4 - Problems
      - text: "---"
      - section: "Labs - Solutions"
        contents:
          - href: Lab1-Solutions.qmd
            text: Lab 1 - Solutions
          - href: Lab2-Solutions.qmd
            text: Lab 2 - Solutions
          - href: Lab3-Solutions.qmd
            text: Lab 3 - Solutions
          - href: Lab4-Solutions.qmd
            text: Lab 4 - Solutions


format:
  html:
    css: styles.css
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    number-sections: true


execute:
  cache: true
  freeze: auto
