---
title: "Lab Assignments"
subtitle: "MA-365/M65: Risk and Survival Models"
format: html
---

# Site overview {.unnumbered}

This site contains Lab assignments and their solutions.

# [Lab 1](Lab1.qmd) {.unnumbered}
In this lab you may learn about the following topics:

* Introduction to R

* Arithmetic operations

* Vectors

* Further operations with vectors

* First steps in plotting

You may try first or proceed straight to solutions [Lab 1 - Solutions](Lab1-Solutions.qmd)


# [Lab 2](Lab2.qmd) {.unnumbered}
In this lab you may learn about the following topics:

* Probability distributions in R: general structures

* Exponential distribution

* Gamma distribution

* Normal and log-normal distributions

* Tou will also learn about `set.seed` function

You may try first or proceed straight to solutions [Lab 2 - Solutions](Lab2-Solutions.qmd) 


# [Lab 3](Lab3.qmd) {.unnumbered}
In this lab you may learn about the following topics:

* Weibull distribution

* Pareto distribution

* How to define a function in R

* How to use an external package

* Loops

You may try first or proceed straight to  [Lab 3 - Solutions](Lab3-Solutions.qmd)


# [Lab 4](Lab4.qmd) {.unnumbered}
In this lab you may learn about the following topics:

* How to create data frame

* How to load an external data frame

* How to access the data from a data frame

* How to filter a data frame

* How to recognise linear dependence between data sets

<!-- You may try first or proceed straight to  [Lab 4 - Solutions](Lab4-Solutions.qmd) -->
